strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'windows-2019'

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'

- script: yarn && yarn test && yarn spec --coverage && yarn codecov -t a35f6c26-7c1c-41fb-8132-11abf0c75afe
