#!/usr/bin/env node

/**
 * Module dependencies.
 */

const { default: program } = require('..');

function range(val) {
  return val.split('..').map(Number);
}

function list(val) {
  return val.split(',');
}

function collect(val, memo) {
  memo.push(val);
  return memo;
}

function increaseVerbosity(v, total) {
  return total + 1;
}

const prog = program()
  .version('0.0.1')
  .usage('test')
  .option('-i, --integer <n>', 'An integer argument', parseInt)
  .option('-f, --float <n>', 'A float argument', parseFloat)
  .option('-r, --range <a>..<b>', 'A range', range)
  .option('-l, --list <items>', 'A list', list)
  .option('-o, --optional [value]', 'An optional value')
  .option('-c, --collect [value]', 'A repeatable value', collect, [])
  .option(
    '-v, --verbose',
    'A value that can be increased',
    increaseVerbosity,
    0
  )
  .init();

console.log(' int: %j', prog.integer);
console.log(' float: %j', prog.float);
console.log(' optional: %j', prog.optional);
prog.range = prog.range || [];
console.log(' range: %j..%j', prog.range[0], prog.range[1]);
console.log(' list: %j', prog.list);
console.log(' collect: %j', prog.collect);
console.log(' verbosity: %j', prog.verbose);
console.log(' args: %j', prog.args);
