#!/usr/bin/env node

/**
 * Module dependencies.
 */

const { default: program } = require('..');

const prog = program()
  .version('0.0.1')
  .option('-f, --foo', 'enable some foo')
  .option('-b, --bar', 'enable some bar')
  .option('-B, --baz', 'enable some baz');

// must be before .init() since
// node's emit() is immediate

prog.on('--help', function() {
  console.log('');
  console.log('Examples:');
  console.log('');
  console.log('  $ custom-help --help');
  console.log('  $ custom-help -h');
});

prog.init();

prog.help();
