#!/usr/bin/env node

/**
 * Module dependencies.
 */

const { default: program } = require('..');

const prog = program()
  .version('0.0.1')
  .option('-C, --chdir <path>', 'change the working directory')
  .option('-c, --config <path>', 'set config path. defaults to ./deploy.conf')
  .option('-T, --no-tests', 'ignore test hook');

prog
  .command('setup [env]')
  .description('run setup commands for all envs')
  .option('-s, --setup_mode [mode]', 'Which setup mode to use')
  .action(function(env = 'all', options) {
    const mode = options.setup_mode || 'normal';
    console.log('setup for %s env(s) with %s mode', env, mode);
  });

prog
  .command('exec <cmd>')
  .alias('ex')
  .description('execute the given remote cmd')
  .option('-e, --exec_mode <mode>', 'Which exec mode to use')
  .action(function(cmd, options) {
    console.log('exec "%s" using %s mode', cmd, options.exec_mode);
  })
  .on('--help', function() {
    console.log('  Examples:');
    console.log();
    console.log('    $ deploy exec sequential');
    console.log('    $ deploy exec async');
    console.log();
  });

prog.command('*').action(function(env) {
  console.log('deploying "%s"', env);
});

prog.init();
