#!/usr/bin/env node

/**
 * Module dependencies.
 */

const { default: program } = require('..');

const prog = program()
  .version('0.0.1')
  .option('-s, --sessions', 'add session support')
  .option(
    '-t, --template <engine>',
    'specify template engine (jade|ejs) [jade]',
    'jade'
  )
  .option(
    '-c, --css <engine>',
    'specify stylesheet engine (stylus|sass|less) [css]',
    'css'
  )
  .init();

console.log(' - sessions %j', prog.sessions);
console.log(' - template %j', prog.template);
console.log(' - css %j', prog.css);
