#!/usr/bin/env node

/**
 * Module dependencies.
 */

const { default: program } = require('..');

const prog = program()
  .version('0.0.1')
  .option('-f, --foo', 'enable some foo')
  .option('-b, --bar', 'enable some bar')
  .option('-B, --baz', 'enable some baz')
  .parse(process.argv);

if (!prog.args.length) prog.help();
