#!/usr/bin/env node

const { default: program } = require('..');

const prog = program.option('-f, --force', 'force installation').init();

const pkgs = prog.args;

if (!pkgs.length) {
  console.error('packages required');
  process.exit(1);
}

console.log();
if (prog.force) console.log('  force: install');
pkgs.forEach(function(pkg) {
  console.log('  install : %s', pkg);
});
console.log();
