#!/usr/bin/env node

/**
 * Module dependencies.
 */

const { default: program } = require('..');

const prog = program()
  .version('0.0.1')
  .usage('test')
  .option('-s --size <size>', 'Pizza size', /^(large|medium|small)$/i, 'medium')
  .option('-d --drink [drink]', 'Drink', /^(coke|pepsi|izze)$/i)
  .parse(process.argv);

console.log(' size: %j', prog.size);
console.log(' drink: %j', prog.drink);
